default_context:
  project_name: 'mystudy'
  project_slug: 'mystudy'
  domain_main: 'mystudy.com'
  domain_staging: 'stag.mystudy.com'
  docker_swarm_stack_name_main: 'mystudy-com'
  docker_swarm_stack_name_staging: 'stag-mystudy-com'
  secret_key: '02720ac080df32f6c9dc97b265a8593971cb8a6ba6d12c46e3b78422333fd9e5'
  first_superuser: 'admin@mystudy.com'
  first_superuser_password: '19870209'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.mystudy.com", "https://stag.mystudy.com", "https://mystudy.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@mystudy.com'
  postgres_password: '19870209'
  pgadmin_default_user: 'admin@mystudy.com'
  pgadmin_default_user_password: '19870209'
  traefik_constraint_tag: 'mystudy.com'
  traefik_constraint_tag_staging: 'stag.mystudy.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:19870209'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
