"""create device and iotdevice

Revision ID: 4c2e4bf0fc5d
Revises: d4867f3a4c0a
Create Date: 2021-05-26 02:16:26.235923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c2e4bf0fc5d'
down_revision = 'd4867f3a4c0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('macaddr', sa.String(), nullable=True),
    sa.Column('activetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expirationtime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_activetime'), 'device', ['activetime'], unique=False)
    op.create_index(op.f('ix_device_description'), 'device', ['description'], unique=False)
    op.create_index(op.f('ix_device_expirationtime'), 'device', ['expirationtime'], unique=False)
    op.create_index(op.f('ix_device_id'), 'device', ['id'], unique=False)
    op.create_index(op.f('ix_device_macaddr'), 'device', ['macaddr'], unique=False)
    op.create_table('iotdevice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sn', sa.String(), nullable=True),
    sa.Column('time', sa.String(), nullable=True),
    sa.Column('identify', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('nfc', sa.String(), nullable=True),
    sa.Column('bluetooth', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_iotdevice_bluetooth'), 'iotdevice', ['bluetooth'], unique=False)
    op.create_index(op.f('ix_iotdevice_id'), 'iotdevice', ['id'], unique=False)
    op.create_index(op.f('ix_iotdevice_identify'), 'iotdevice', ['identify'], unique=False)
    op.create_index(op.f('ix_iotdevice_message'), 'iotdevice', ['message'], unique=False)
    op.create_index(op.f('ix_iotdevice_nfc'), 'iotdevice', ['nfc'], unique=False)
    op.create_index(op.f('ix_iotdevice_sn'), 'iotdevice', ['sn'], unique=False)
    op.create_index(op.f('ix_iotdevice_time'), 'iotdevice', ['time'], unique=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_iotdevice_time'), table_name='iotdevice')
    op.drop_index(op.f('ix_iotdevice_sn'), table_name='iotdevice')
    op.drop_index(op.f('ix_iotdevice_nfc'), table_name='iotdevice')
    op.drop_index(op.f('ix_iotdevice_message'), table_name='iotdevice')
    op.drop_index(op.f('ix_iotdevice_identify'), table_name='iotdevice')
    op.drop_index(op.f('ix_iotdevice_id'), table_name='iotdevice')
    op.drop_index(op.f('ix_iotdevice_bluetooth'), table_name='iotdevice')
    op.drop_table('iotdevice')
    op.drop_index(op.f('ix_device_macaddr'), table_name='device')
    op.drop_index(op.f('ix_device_id'), table_name='device')
    op.drop_index(op.f('ix_device_expirationtime'), table_name='device')
    op.drop_index(op.f('ix_device_description'), table_name='device')
    op.drop_index(op.f('ix_device_activetime'), table_name='device')
    op.drop_table('device')
    # ### end Alembic commands ###
